CarBooking/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CarBooking.Models;

namespace CarBooking.Controllers
{
    public class CarsController : Controller
    {
       


        public IActionResult Index()
        {
            var cars = DbContext.Cars;
            return View(cars);
        }

        public IActionResult Create()
        {
            return View();
        }

        



        [HttpPost] public IActionResult Create(Car car)
        {
            if (ModelState.IsValid)
            {
                car.Id = Guid.NewGuid();
                DbContext.Cars.Add(car);
                return RedirectToAction("Index");
            }

            return View(car);
        }

        public IActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = DbContext.Cars.FirstOrDefault(c => c.Id == id);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

       
        [HttpPost]
        public IActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                var carIndex = DbContext.Cars.FindIndex(c => c.Id == car.Id);

                if (carIndex == -1)
                {
                    return NotFound();
                }

                DbContext.Cars[carIndex] = car;

                return RedirectToAction(nameof(Index));
            }

            return View(car);
        }


        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = DbContext.Cars.FirstOrDefault(c => c.Id == id);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }


        [HttpPost]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var car = DbContext.Cars.FirstOrDefault(c => c.Id == id);

            if (car == null)
            {
                return NotFound();
            }

            DbContext.Cars.Remove(car);

            return RedirectToAction("Index");
        }
        
        }


    }

CarBooking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CarBooking.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CarBooking/Controllers/RentalsController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using CarBooking.Helpers;
using CarBooking.Models;
using CarBooking.Models.ViewModels;


namespace CarBooking.Controllers
{
    public class RentalsController : Controller
    {
        public IActionResult Index()
        {
            var rentals = DbContext.Rentals;
            return View(rentals);
        }

        public IActionResult Create()
        {
            var newRentalViewModel = new NewRentalViewModel() { Cars = DbContext.Cars };
            return View(newRentalViewModel);

        }

        [HttpPost]
        public IActionResult Create(Rental rental)
        {
            var car = DbContext.Cars.FirstOrDefault(c => c.Id == rental.CarId);
            rental.Id = Guid.NewGuid();

            rental.CarModel = car.Model;

            DbContext.Rentals.Add(rental);

            return RedirectToAction("Index");

        }

        private bool ValidateBooking(Rental rental)
        {
            bool isValid = true;

           
            if (rental.From > rental.To)
            {
                ModelState.AddModelError("Booking.From", "Start date cannot be after end date");
                var newRentalViewModel = new NewRentalViewModel() { Cars = DbContext.Cars, Rental = rental };
                isValid = false;
            }

            
            List<Rental> rentalFromDb = DbContext.Rentals.Where(r => r.CarId == rental.CarId).ToList();

            
            foreach (var currentRentals in rentalFromDb)
            {
                if (DateHelpers.HasSharedDateIntervals(rental.From, rental.To, currentRentals.From, currentRentals.To))
                {
                    ModelState.AddModelError("Booking.From", "Date already occupied.");
                    var newRentalViewModel = new NewRentalViewModel() { Cars = DbContext.Cars, Rental = rental };
                    isValid = false;
                }
            }

            return isValid;
        }
        public IActionResult Edit(Guid id)
        {
         
            var rental = DbContext.Rentals.FirstOrDefault(r => r.Id == id);

            var EditRentalViewModel = new EditRentalViewModel() { Rental = rental, Cars = DbContext.Cars};
            return View(EditRentalViewModel);



        }
        [HttpPost]
        public IActionResult Edit(Rental rental)
        {
            rental.CarModel = DbContext.Cars.FirstOrDefault(cM => cM.Id == rental.CarId).Model;

            var rentalId = DbContext.Rentals.FindIndex(rI => rI.Id == rental.Id);

            if (rentalId == -1)
            {
                return NotFound();
            }

            DbContext.Rentals[rentalId] = rental;

            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = DbContext.Rentals.FirstOrDefault(c => c.Id == id);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var rental = DbContext.Rentals.FirstOrDefault(r => r.Id == id);

            if (rental == null)
            {
                return NotFound();
            }

            DbContext.Rentals.Remove(rental);

            return RedirectToAction("Index");
        }


    }
}

CarBooking/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

@model IEnumerable<Car>

<html>
<body>
    <h1>Car Rental</h1>

    <main class="homescreen">

        <section class="homeLeftSection">
            <video class="homeScreenVideo" controls autoplay loop>
                <source src="~/videos/IntroVideo.mp4" type="video/mp4">
                Your browser does not support the video tag.
            </video>
        </section>


        <section class="homeRightSection">

            <h3 class="flex-fill">Economy Is Our First Name</h3>
            <p class="flex-fill">
                One of our top priorities is to adjust each package we offer to our customer’s exact needs.
                We offer a variety of options that can enhance your experience, Always according to your necessities,
                and help you get the best out of your holidays or your business trip.
            </p>

            <h3 class="flex-fill">Book Safe And Easy</h3>
            <p class="flex-fill">
                Our smart booking engine searches for the best price, car category, extras,
                exclusive offers and discounts suiting your needs.
                You can securely book online today
                and pay upon your arrival at the desk!
            </p>

        </section>


    </main>

    <div class="homeInformation">

        <div>
            <a class="homeScreenToGarage" asp-controller="Cars" asp-action="Index"><h2>View our car collection</h2></a>
        </div>

        <div>
            <a class="homeScreenToRental" asp-controller="Rentals" asp-action="Index"><h2>Rent a car</h2></a>
        </div>

    </div>

    <p class="motto">Because we believe in making traveling easier</p>
</body>
</html>